export const LOGIN_MODAL = "LOGIN_MODAL";
export const REGISTRATION_MODAL = "REGISTRATION_MODAL";
export const CHAT_MODAL = "CHAT_MODAL";
export const USER_PARAMS = "USER_PARAMS";
export const NOTIFICATIONS_MODAL = "NOTIFICATIONS_MODAL";
export const FIND_TASK_FROM_MY_ORDERS = "FIND_TASK_FROM_MY_ORDERS"